out_dir: results/TMDM_neuronal
dataset:
  file_path: ["dataset/spdata_sde_neuronal"]
  filter: ["*"]
  sampling_t: [10]
  windows: [100]
  pred_len: [100]
  interval_step: [ 100 ]
  F_consistency: [ False ]
train:
  model_evaluation: ["hold_out"]
  train_model_select: ["TMDM_model"]
  traindata_size: [0.8]
  train_batch_size: [512]
  val_batch_size: [512]
  train_epochs: [50]
  test_set: [True]
  ckpt: [False]
  ckpt_period: [2]
  dataparallel: [False]
  pretrain_path: ["None"]
  pretrain_model: ["None"]
net:
  device: ["cuda:1"]
  scaler_type: ["StandardScaler"]
  task_model: ["TMDM"]
  pretrain_f_path: ["None"]
  pretrain_g_path: ["None"]
  n_z_samples: [100]
  parallel_sample: [10]
  diffusion_steps: [20]
  beta_start: [0.0001]
  beta_end: [0.02]
  beta_schedule: ["linear"]
  embed: ["fixed"]
  freq: ["h"]
  dropout: [0.05]
  output_attention: [False]
  d_model: [64]
  CART_input_x_embed_dim: [64]
  factor: [3]
  n_heads: [4]
  d_ff: [128]
  activation: ["gelu"]
  e_layers: [2]
  d_layers: [1]
  p_hidden_dims: [[64, 64]]
  p_hidden_layers: [2]
  d_z: [64]
  k_z: [0.01]
  k_cond: [1.0]
  diffusion_config_dir: ["models/Diffusion_model/TMDM/tmdm.yml"]
loss:
  loss_metric: ["TMDM loss"]
optimizer:
  optimizer_name: [Adam]
  lr: [0.0001]
  weight_decay: [1e-5]
  scheduler_set: [False]
  scheduler: [MultiStepLR]
  MstepLR_milestones: [[10]]
  MstepLR_gamma: [0.1]
