out_dir: results/DiffusionTS_bio
dataset:
  file_path: ["dataset/spdata_sde_biomass"]
  filter: ["*"]
  sampling_t: [10]
  windows: [100]
  pred_len: [100]
  interval_step: [100]
  F_consistency: [False]
  data_dropout:  [0.1]
train:
  model_evaluation: ["hold_out"]
  train_model_select: ["DiffusionTS_model"]
  traindata_size: [0.8]
  train_batch_size: [512]
  val_batch_size: [512]
  train_epochs: [50]
  test_set: [True]
  ckpt: [False]
  ckpt_period: [2]
  dataparallel: [False]
  pretrain_path: ["None"]
  pretrain_model: ["None"]
net:
  device: ["cuda:3"]
  scaler_type: ["StandardScaler"]
  task_model: ["DiffusionTS"]
  pretrain_f_path: ["None"]
  pretrain_g_path: ["None"]
  n_z_samples: [100]
  parallel_sample: [10]
  timesteps: [100]
  diffusion_steps: [20]
  n_layer_enc: [3]
  n_layer_dec: [6]
  d_model: [64]
  loss_type: ["l2"]
  beta_schedule: ["cosine"]
  n_heads: [4]
  mlp_hidden_times: [4]
  eta: [0.0]
  attn_pd: [0.0]
  resid_pd: [0.0]
  kernel_size: [null]
  padding_size: [null]
  use_ff: [True]
  reg_weight: [null]
  infill_coef: [0.1]
  infill_learning_rate: [0.05]
loss:
  loss_metric: ["DiffusionTS loss"]
optimizer:
  optimizer_name: [Adam]
  lr: [0.0001,0.001]
  weight_decay: [1e-5]
  scheduler_set: [False]
  scheduler: [MultiStepLR]
  MstepLR_milestones: [[10]]
  MstepLR_gamma: [0.1]
