dataset:
  F_consistency: false
  data_dropout: 1
  file_path: dataset/spdata_sde_biomass
  filter: '*'
  interval_step: 100
  pred_len: 100
  sampling_t: 10
  windows: 100
loss:
  loss_metric: KL divergence
net:
  activation: gelu
  beta_end: 0.02
  beta_start: 0.0001
  d_ff: 256
  d_layers: 2
  d_model: 512
  dataset_nf: 1
  device: cuda
  diffusion_schedule: linear
  diffusion_steps: 20
  dropout: 0.05
  e_layers: 4
  factor: 3
  freeze_pretrain: false
  load_pretrain: false
  n_heads: 8
  n_z_samples: 100
  output_attention: false
  p_hidden_dims:
  - 64
  - 64
  p_hidden_layers: 2
  parallel_sample: 10
  pred_len: 100
  pretrain_f_path: results/pre_model_F/dataset__w100p100st10
  pretrain_g_path: results/pre_model_g/dataset__w100p100st10
  rolling_length: 50
  scaler_type: StandardScaler
  task_model: NsDiff
  windows: 100
optimizer:
  MstepLR_gamma: 0.1
  MstepLR_milestones:
  - 10
  lr: 0.001
  optimizer_name: Adam
  scheduler: MultiStepLR
  scheduler_set: false
  weight_decay: 1e-5
train:
  ckpt: true
  ckpt_period: 10
  model_evaluation: hold_out
  test_set: true
  train_batch_size: 2160
  train_epochs: 100
  train_model_select: NsDiff_model
  traindata_size: 0.8
  val_batch_size: 2160
